### ISSUE TITLE
pubkey

### ISSUE THREAD

**Issue by gilsilva20629** [gilsilva20629/nostr#2]
Received: ["OK","dbe32e67d52c389074fdc3b09726d910b118a3d6313a1544344194286b0fc851",false,"invalid: verify sig: bad pubkey"]

**Comment by misesdev** [comment]
Fala man, consegue me adicionar como contribuidor pra mim poder fazer pull request? fiz algumas melhorias com comentários explicando

**Comment by misesdev** [comment]
Você está passando no campo pubkey o hash sha256 da chave pública, e oque é experado é a sua chave pública comprimida.

 "pubkey": <32-bytes lowercase hex-encoded public key of the event creator>,
 
 Um par de chaves em curva eliptca é composto por um número que indica a quantidade de vezes que você faz interceções em um plano cartesiano(chave pública), e a posição final eixo X e Y(chave pública).
 
Por tanto a chave privada é um número de 32 bytes, e a chave pública são dois número de 32 bytes concatenados com o prefixo que indica a ordem(se X é o primeiro número ou se é Y por exemplo), completando 65 bytes, sendo 1 byte de prefixo e 32 bytes para cada número.
 
Em um plano cartesiano, existe um cálculo em que dado a posição X você consegue deduzir a posição Y, e também dado uma posição Y, você consegue deduzir a posição X, Por isso chave pública comprimida, é um array de bytes com 33 bytes, sendo o primeiro byte um prefixo que indica se aquele é o número X ou Y, e os 32 bytes do número em se.
 
No caso do evento nostr ele recebe a chave pública comprimida de 32 bytes, ou seja, não há prefixo indicando qual a posição(X ou Y), o protocolo já determina que deve receber a posição X de 32 bytes.

Na bibliotéca que você está utilizando, não tem opção de pegar apenas X, da chave pública, então você deve pegar a chave não comprimida, e então, ignorar primeiro byte de prefixo, e pegar os próximos 32 bytes que é o número X da chave pública.

Isso resolve o problema da chave pública, porém a sua bibliotéca deve estár com algum problema, ou alguma conversão de unicode que dá um resultado diferente de chave pública, teste no link que mandei acima, gerando uma chave privada e verificando a chave pública gerada pelo site do link, ou pesquise em outras fontes.

Fiz um pull request para o seu repositório com um resumo dessas anotações e alterações.
